version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quantivo_db
    environment:
      POSTGRES_DB: quantivo_db
      POSTGRES_USER: quantivo_user
      POSTGRES_PASSWORD: quantivo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantivo_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: quantivo_backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8009:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=http://38.242.200.152:8009/api
    container_name: quantivo_frontend
    ports:
      - "8089:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: