# Generated by Django 4.2.11 on 2026-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('stack', models.JSONField(default=list)),
                ('tag', models.CharField(max_length=50)),
                ('tag_color', models.CharField(default='#4F46E5', max_length=7)),
                ('gradient', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Cases',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
