# Generated by Django 4.2.11 on 2026-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(max_length=10)),
                ('tag_color', models.CharField(default='#E11D48', max_length=7)),
                ('accent_bg', models.CharField(default='#FFF1F2', max_length=7)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenges', models.JSONField(default=list)),
                ('solutions', models.JSONField(default=list)),
                ('stats', models.JSONField(default=list)),
                ('case_study', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'name'],
            },
        ),
    ]
