# Generated by Django 4.2.11 on 2026-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('category_color', models.CharField(default='#7C3AED', max_length=7)),
                ('author', models.CharField(max_length=100)),
                ('author_avatar', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
